#!/bin/bash

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}AI Flashcards App - Setup Script${NC}"
echo "This script will help you set up your environment variables."
echo ""

# Check if .env.local exists
if [ -f .env.local ]; then
  echo -e "${YELLOW}A .env.local file already exists.${NC}"
  read -p "Do you want to overwrite it? (y/n): " overwrite
  if [[ $overwrite != "y" && $overwrite != "Y" ]]; then
    echo -e "${RED}Setup aborted.${NC}"
    exit 1
  fi
fi

echo ""
echo -e "${GREEN}Please provide the following information:${NC}"
echo ""

# Get Supabase URL
read -p "Supabase Project URL: " supabase_url

# Get Supabase Anon Key
read -p "Supabase Anon Key: " supabase_anon_key

# Get OpenRouter API Key
read -p "OpenRouter API Key (leave blank if you don't have one yet): " openrouter_api_key

# Create .env.local file
echo "# Generated by setup.sh" > .env.local
echo "NEXT_PUBLIC_SUPABASE_URL=$supabase_url" >> .env.local
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$supabase_anon_key" >> .env.local

if [ -n "$openrouter_api_key" ]; then
  echo "NEXT_PUBLIC_OPENROUTER_API_KEY=$openrouter_api_key" >> .env.local
fi

echo ""
echo -e "${GREEN}Environment variables have been saved to .env.local${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "1. Install dependencies: npm install"
echo "2. Start the development server: npm run dev"
echo "3. Open http://localhost:3000 in your browser"
echo ""
echo -e "${GREEN}Happy learning with AI Flashcards!${NC}" 